version: 2

models:
  - name: order_details
    description: "Fact table combining orders, products, and day-level context"
    columns:
      - name: order_id
        tests: [not_null]
      - name: user_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: day_name
        description: "Name of the day from dim_time"
      - name: is_weekend
        description: "TRUE if order was placed on weekend"
